class Coffee {
	{field} name : String
    {field} conds : String[]
    {method} String getName()
    {method} String[] getConds()
}

class Controller {
	...
}

class CPS {
	{method} void processOrder(String coffeeName, String[] ingredients, int[] amounts)
	{method} void setMachineSelectionStrategy(MachineSelectionStrategy s)
	{method} ...
}

CPS --> "*" Machine : machines

class Machine {
	{field} name : String
	{method} String getName()
}

class MainRunner {
	{method} void getCoffeeList()
	{method} void getMachineList()
}

MainRunner --> "*" Coffee : coffees

interface OrderObserver {
    {method} void makeOrder(String name, String[] ingredients, int[] amounts)
}

Machine ..|> OrderObserver

interface OrderSubject {
	{method} addOrderObserver(OrderObserver o)
    {method} removeOrderObserver(OrderObserver o)
    {method} processOrder()
}

CPS ..|> OrderSubject
CPS --> "1" MachineSelectionStrategy : strategy

interface MachineSelectionStrategy {
	{method} void processOrder(String coffeeName, String[] ingredients, int[] amounts)
}

class NearestCoffeeMachine {
	{method} ...
}

class HighestRatedCoffeeMachine {
	{method} ...
}

NearestCoffeeMachine ..|> MachineSelectionStrategy
HighestRatedCoffeeMachine ..|> MachineSelectionStrategy
